# Generated by Django 5.1.4 on 2025-09-16 06:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('personapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='person',
            options={'managed': False},
        ),
    ]
