# Generated by Django 4.2.24 on 2025-09-16 08:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('personapp', '0002_alter_person_options'),
    ]

    operations = [
    ]
